module.exports ={
    filetypes :[
        {EXTN : "PDF", CONTENT_TYPE:'application/pdf'},
        {EXTN : "XLSX", CONTENT_TYPE:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},
        {EXTN : "DOC", CONTENT_TYPE:'application/msword'},
        {EXTN : "DOCX", CONTENT_TYPE:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'},
        {EXTN : "XLS", CONTENT_TYPE:'application/vnd.ms-excel'},
        {EXTN : "XLSX", CONTENT_TYPE:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},
        {EXTN : "PPT", CONTENT_TYPE:'application/vnd.ms-powerpoint'},
        {EXTN : "PPTX", CONTENT_TYPE:'application/vnd.openxmlformats-officedocument.presentationml.presentation'},
        {EXTN : "GIF", CONTENT_TYPE:'image/gif'},
        {EXTN : "JPEG", CONTENT_TYPE:'image/jpeg'},
        {EXTN : "PNG", CONTENT_TYPE:'image/png'},
        {EXTN : "JPG", CONTENT_TYPE:'image/jpeg'},
        {EXTN : "TXT", CONTENT_TYPE:'text/plain'},
        {EXTN : "MP4", CONTENT_TYPE:'video/mp4'},
        {EXTN : "MP3", CONTENT_TYPE:'audio/mp3'},
        {EXTN : "MP4A", CONTENT_TYPE:'audio/mp4'},
        {EXTN : "M4A", CONTENT_TYPE:'audio/mp4'},
        {EXTN : "M4V", CONTENT_TYPE:'video/x-m4v'},
        {EXTN : "F4V", CONTENT_TYPE:'video/x-f4v'},
        {EXTN : "F4A", CONTENT_TYPE:'audio/x-f4a'},
        {EXTN : "M4B", CONTENT_TYPE:'audio/mp4'},
        {EXTN : "M4P", CONTENT_TYPE:'audio/mp4'},
        {EXTN : "M4R", CONTENT_TYPE:'audio/mp4'},
        {EXTN : "F4B", CONTENT_TYPE:'audio/x-f4a'},
        {EXTN : "AVI", CONTENT_TYPE:'video/x-msvideo'},
        {EXTN : "MOV", CONTENT_TYPE:'video/quicktime'},
        {EXTN : "QT",  CONTENT_TYPE:'video/quicktime'},
        {EXTN : "MOVE", CONTENT_TYPE:'video/x-sgi-movie'},
        {EXTN : "3GP", CONTENT_TYPE:'video/3gpp'},
        {EXTN : "3GP2", CONTENT_TYPE:'video/3gpp2'},
        {EXTN : "3G2", CONTENT_TYPE:'video/3gpp'},
        {EXTN : "3GPP", CONTENT_TYPE:'video/3gpp'},
        {EXTN : "3GPP2", CONTENT_TYPE:'video/3gpp2'},
        {EXTN : "OGG", CONTENT_TYPE:'application/ogg'},
        {EXTN : "OGA", CONTENT_TYPE:'audio/ogg'},
        {EXTN : "OGV", CONTENT_TYPE:'video/ogg'},
        {EXTN : "OGX", CONTENT_TYPE:'application/ogg'},
        {EXTN : "WMV", CONTENT_TYPE:'video/x-ms-wmv'},
        {EXTN : "WMA", CONTENT_TYPE:'audio/x-ms-wma'},
        {EXTN : "ASF", CONTENT_TYPE:'video/x-ms-asf'},    
        {EXTN : "ZIP", CONTENT_TYPE:'application/zip'},    
        {EXTN : "RAR", CONTENT_TYPE:'application/x-rar-compressed'}
    ]
};